### PR TITLE
cut extension from link

### PR DESCRIPTION
**Pull request by vadim-zyamalov**
Hello! Thanks for your script :smile:

There is an option `g:vimwiki_markdown_link_ext` which configures `vimwiki` to add `.md` extensions to links for the sake of compatibility with other markdown tools.

However it breaks links in generated html files as `vimwiki` wipes the extension from filenames but not from links themselves. My small patch to your script wipes the `.md` from links as well.

### CODE REVIEW

**Comment by vadim-zyamalov** [comment]
My first commit didn't respect `EXTENSION` argument. Now with making it global it's the correct extension that is stripped.

**Comment by WnP** [comment]
Hello @d9d6ka,

Thanks for your contribution. Here is my feedback on it:

- I prefer not using global variables
- need to remove the old comment which say that it's not implemented
- rebase to squash all the commits

Here is a simple patch:

```diff
diff --git a/vimwiki_markdown.py b/vimwiki_markdown.py
index cae81f3..a441ab7 100644
--- a/vimwiki_markdown.py
+++ b/vimwiki_markdown.py
@@ -46,11 +46,19 @@ else:
 class LinkInlineProcessor(markdown.inlinepatterns.LinkInlineProcessor):
     """Fix wiki links"""

+    def __init__(self, *args, extension="md", **kwargs):
+        if not extension.startswith("."):
+            extension = f".{extension}"
+        self.extension = extension
+        return super().__init__(*args, **kwargs)
+
     def getLink(self, *args, **kwargs):
         href, title, index, handled = super().getLink(*args, **kwargs)
         if not href.startswith("http") and not href.endswith(".html"):
             if auto_index and href.endswith("/"):
                 href += "index.html"
+            elif href.endswith(self.extension):
+                href = href[: -len(self.extension)] + ".html"
             elif not href.endswith("/"):
                 href += ".html"
         return href, title, index, handled
@@ -64,7 +72,7 @@ def main():

     FORCE = sys.argv[1]  # noqa - not supported
     SYNTAX = sys.argv[2]
-    EXTENSION = sys.argv[3]  # noqa - not supported
+    EXTENSION = sys.argv[3]
     OUTPUT_DIR = sys.argv[4]
     INPUT_FILE = sys.argv[5]
     CSS_FILE = sys.argv[6]  # noqa - not supported
@@ -101,7 +109,11 @@ def main():
     md = markdown.Markdown(extensions=extensions)
     md.inlinePatterns.deregister("link")
     md.inlinePatterns.register(
-        LinkInlineProcessor(markdown.inlinepatterns.LINK_RE, md), "link", 160
+        LinkInlineProcessor(
+            markdown.inlinepatterns.LINK_RE, md, extension=EXTENSION
+        ),
+        "link",
+        160,
     )

     with open(INPUT_FILE, "rb") as f:
```

I want to preserve your name in the contributor list, that's why I prefer asking you for those changes rather that doing it myself.

**Comment by vadim-zyamalov** [comment]
Thanks! I've rewritten my patch to eliminate global variable and follow your suggestions.
I've also included a patch from my PR #13, so the current PR closes it as well.

**Comment by WnP** [comment]
In fact I prefer the two feature to be separated, see my comment on #13 

Thanks

**Comment by d9d6ka** [comment]
Ok, I'll separate then in a couple of hours.

**Comment by vadim-zyamalov** [comment]
> In fact I prefer the two feature to be separated, see my comment on #13
> 
> Thanks

Done. I've eliminated #13 from this PR.

Thanks!

**Pull request closed without merging**
